{% set name = "qlient" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qlient-{{ version }}.tar.gz
  sha256: e23ae92e70cc909b866a70db6e2fd6b4832cf14d36596427ba3879be499966d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7,<4.0
    - qlient-core >=1.0.1,<2.0.0
    - requests >=2.27.1,<3.0.0
    - websocket-client >=1.3.3,<2.0.0

test:
  imports:
    - qlient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://qlient-org.github.io/python-qlient/
  summary: A fast and modern graphql client designed with simplicity in mind.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
